server:
  port: ${SERVER_PORT:8666}
spring:
  application:
    name: myvote
  flyway:
    placeholders:
      db: ${DB_NAME:myvote}
      schema: postgres
      user: ${DB_USER:example}
    out-of-order: ${FLYWAY_OUT_OF_ORDER:false}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myvote}?currentSchema=${DB_SCHEMA:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}


  jpa:
    properties:
      hibernate.default_schema: ${DB_SCHEMA:postgres}
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: error
    org.hibernate: error
  file:
    name: /log/skillscanner-service.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 1000MB

openapi:
  info:
    title: Backend for rosatom myvote
    version: 1.0.0
    contact:
      name: Kvashnin Denis
      email: denis.kvashnin.1994@yandex.ru
    tags:
      name: Rosatom
      description: Backend for rosatom myvote service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator

springdoc:
  enable-kotlin: false

integration:
  analytics:
    url: https://myvote-analytics.kovalev.team
  profanity:
    url: https://myvote-profanity.kovalev.team

